apiVersion: v1
kind: Service
metadata:
  name: patidosa-service
spec:
  type: LoadBalancer   # use NodePort instead if not on a cloud provider with LB support
  selector:
    app: patidosa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
